import {ProjectObject} from '../../modals/blogs'

const ProjectsList: ProjectObject[] = [
    {
        id: 'sobyte',
        year: 2022,
        title: 'Sobyte',
        techstacks: [
            'React-Native',
            'Firebase',
            'MySQL',
            'Typescript',
            'Express',
            'Google Cloud',
        ],
        iconType: 'android',
        link: 'https://github.com/sobhanbera',
        github: 'https://github.com/sobhanbera',
        playstore: '',
        org: 'Sobyte',
        orgURL: 'https://github.com/sobhanbera',
        description:
            'Creating a full-fledged online music streaming android app. Realtime search suggestions, Themes, Customization and more...',
    },
    {
        id: 1,
        year: 2022,
        title: 'Sukrishak',
        techstacks: ['React Native', 'Java', 'Typescript', 'MySQL'],
        iconType: 'android',
        link: 'https://sih.gov.in/sih2022PS?technology_bucket=MQ==&category=U29mdHdhcmU=&organization=QUlDVEUsIE1JQy1TdHVkZW50IElubm92YXRpb24=&organization_type=QWxs',
        org: 'SIH India',
        orgURL: 'https://sih.gov.in',
        description:
            'A minimal and simple android app for farmer to help them get resources easily.',
    },
    {
        id: 2,
        year: 2022,
        title: 'Sukrishak Backend',
        techstacks: ['Express', 'Typescript', 'MySQL'],
        iconType: 'web',
        link: 'https://sih.gov.in/sih2022PS?technology_bucket=MQ==&category=U29mdHdhcmU=&organization=QUlDVEUsIE1JQy1TdHVkZW50IElubm92YXRpb24=&organization_type=QWxs',
        org: 'SIH India',
        orgURL: 'https://sih.gov.in',
        description:
            'A separate project for the backend of the Sukrishak android app. Uses MySQL as database and Express.JS as the Backend.',
    },
    {
        id: 'dotfiles',
        year: 2022,
        title: 'Linux Dotfiles',
        techstacks: ['Lua', 'Vim Script'],
        iconType: 'code',
        link: 'https://github.com/sobhanbera/dotfiles',
        github: 'https://github.com/sobhanbera/dotfiles',
        org: 'sobhanbera',
        orgURL: 'https://github.com/sobhanbera',
        description:
            'My full collection of dotfiles and configuration files I used in Arch Linux. Some of the dotfiles are still in use for Neovim (MacOS).',
    },
    {
        id: 3,
        year: 2020,
        title: 'GiftImages Android App',
        techstacks: [
            'Next.js',
            'Node.js',
            'Javascript',
            'MySQL',
            'AWS',
            'CDN',
            'CPanel',
        ],
        iconType: 'android',
        link: 'https://giftimage.in',
        org: 'AICPE',
        orgURL: 'https://www.aicpeindia.ac.in',
        description:
            'An android app to download, rate & customize professional images, built with react-native.',
    },
    {
        id: 3,
        year: 2020,
        title: 'GiftImages Admin',
        techstacks: [
            'Next.js',
            'Node.js',
            'Javascript',
            'MySQL',
            'AWS',
            'CDN',
            'CPanel',
        ],
        iconType: 'web',
        link: 'https://giftimage.in?login=true',
        org: 'AICPE',
        orgURL: 'https://www.aicpeindia.ac.in',
        description:
            'The admin side of the Giftimage android app. Here all users accounts, images data, stats, reports are handled.',
    },
    {
        id: 4,
        year: 2021,
        title: 'Community Forum',
        techstacks: ['Next.js', 'Express', 'MySQL', 'EC2', 'AWS', 'VMs'],
        iconType: 'web',
        link: 'https://community-enord-ai.vercel.app',
        org: 'Enord.ai',
        description:
            'A community website, where students/researchers studying about Drones can ask & answer questions.',
    },
    {
        id: 5,
        year: 2022,
        title: 'DSC-GHRCE Official Website',
        techstacks: [
            'Next.js',
            'Typescript',
            'SCSS',
            'Firebase Auth',
            'Firebase Firestore',
            'AOS',
            'Youtube API',
            'Medium API',
            'Linktree',
        ],
        iconType: 'web',
        link: 'https://dscghrce.vercel.app',
        org: 'sobhanbera',
        description:
            'This is the official website of Google Developer Student Clubs GHRCE. Contains many themes, animations, simple and minimal UI.',
    },
    {
        id: 6,
        year: 2021,
        title: 'Blogging Website',
        techstacks: [
            'Next.js',
            'SCSS',
            'HTML',
            'Animations',
            'Simple',
            'Firebase Realtime DB',
            'Minimal UI',
        ],
        iconType: 'web',
        link: 'https://sobhanblogs.vercel.apps',
        org: 'sobhanbera',
        description:
            'My personal blogging website built with Next.JS and Firebase. All the blogs are taken from my own Medium profile and other bloggins websites.',
    },
    {
        id: 7,
        year: 2022,
        title: 'Portfolio-v2',
        techstacks: [
            'Next.js',
            'SCSS',
            'Animations',
            'Blogs',
            'Themes',
            'Firebase Auth',
            'Firebase Firestore',
        ],
        iconType: 'web',
        link: 'https://sobhanbera.github.io',
        org: 'sobhanbera',
        description:
            'My new portfolio website built with Next.JS. A website full of animations, smooth transitions, UI and more.',
    },
    {
        id: 8,
        year: 2020,
        title: 'Portfolio-v1',
        techstacks: [
            'React.js',
            'CSS',
            'HTML',
            'Animations',
            'Firebase Realtime DB',
        ],
        iconType: 'web',
        link: 'https://sobhanbera1.vercel.app',
        org: 'sobhanbera',
        description:
            'My first try to create a astonishing user-interface in the form of portfolio website. I hope you will like this.',
    },
    {
        id: 'socbyte',
        year: 2020,
        title: 'Socbyte',
        techstacks: [
            'React-Native',
            'Firebase',
            'MySQL',
            'Javascript',
            'Node.JS',
        ],
        iconType: 'android',
        link: 'https://play.google.com/store/apps/details?id=com.socbyte',
        github: 'https://github.com/Socbyte/socbyte-native',
        playstore: 'https://play.google.com/store/apps/details?id=com.socbyte',
        org: 'Socbyte',
        orgURL: 'https://github.com/socbyte',
        description:
            'An android application build with react-native for listening to songs all around the world for free. You can listen to any song anytime and anywhere.',
    },
    {
        id: 'socbyte-backend',
        year: 2020,
        title: 'Socbyte-Backend',
        techstacks: [
            'Javascript',
            'Express',
            'YT-Music-API',
            'Node.JS',
            'Heroku',
        ],
        iconType: 'web',
        link: 'https://socbyte-backend.herokuapp.com',
        github: 'https://github.com/Socbyte/socbyte-backend',
        org: 'Socbyte',
        orgURL: 'https://github.com/socbyte',
        description:
            "It's an open source project which is the working backend of the Socbyte android application. It's basically an Rest-API which provides music data to the frontend.",
    },
    {
        id: 9,
        year: 2020,
        title: 'Minesweeper',
        techstacks: ['React.js', 'CSS', 'HTML', 'Levels', 'Game'],
        iconType: 'web',
        link: 'https://tminesweeper.vercel.app',
        org: 'sobhanbera',
        description:
            'Game totally made for timepass. I was bored so created this simple game to play. Nothing much just a game!',
    },
    {
        id: 10,
        year: 2020,
        title: 'Telebyte Core',
        techstacks: [
            'React.js',
            'CSS',
            'HTML',
            'Firebase Auth',
            'Firebase Realtime DB',
        ],
        iconType: 'web',
        link: 'https://telebyte.vercel.app',
        org: 'Telebyte',
        description:
            'This is the 2nd and the last version of the Telebyte build with React.js on the early days of my learning journey. Might be down due to firebase rules...',
    },
    {
        id: 11,
        year: 2019,
        title: 'Telebyte',
        techstacks: [
            'React.js',
            'CSS',
            'HTML',
            'Firebase Auth',
            'Firebase Realtime DB',
        ],
        iconType: 'web',
        link: 'https://telebytewebold.vercel.app',
        org: 'Telebyte',
        description:
            'First ever production ready social media website. Simple website for chating and more...',
    },
]

export {ProjectsList}
